apiVersion: v1
kind: ConfigMap
metadata:
  name: dist-scheduler
  namespace: dist-scheduler
data:
  ENV: "production"
  PORT: "8080"
  WORKER_COUNT: "5"
  POLL_INTERVAL_SEC: "1"
  MAGIC_LINK_BASE_URL: "https://job.enkiduck.com"
  METRICS_PORT: "9090"
