apiVersion: v1
kind: Secret
metadata:
  name: dist-scheduler
  namespace: dist-scheduler
type: Opaque
stringData:
  POSTGRES_USER: root
  POSTGRES_PASSWORD: root
  POSTGRES_DB: scheduler
  DATABASE_URL: "postgres://root:root@postgres:5432/scheduler?sslmode=disable"
