apiVersion: v1
kind: Secret
metadata:
  name: dist-scheduler
  namespace: dist-scheduler
type: Opaque
stringData:
  POSTGRES_USER: scheduler
  POSTGRES_PASSWORD: scheduler
  POSTGRES_DB: scheduler
  DATABASE_URL: "postgres://scheduler:scheduler@postgres:5432/scheduler?sslmode=disable"
  JWT_SECRET: 3f6ef4a9b68cd6bb42988901c8b70548ddfbeaefdf6528f938fc4bf201a92ba4
  RESEND_API_KEY: CHANGE_ME
  RESEND_FROM: noreply@enkiduck.com
