apiVersion: v1
kind: Secret
metadata:
    name: dist-scheduler
    namespace: dist-scheduler
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:Y3GTogVM34db,iv:iq29nUcwlMUYZ0j8OyAipiDkmJ25QeCaac6I/GAlj1Y=,tag:D981U4xC0M6IjLkwlg5DkA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:TEmeutSxadSWeR0atgsoKKm0AKFPRknP,iv:dSPfJ+6PE67m95h8VH+tkyvitDqaZGPFxPRmRerKjgw=,tag:fdnejr3TX0Va4PD/VbW06A==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:C8T5t6tSQVYf,iv:qZDVnY+eu33+JfZ7lHO8/ieeKk9+SVfsMKFAFpmIRLs=,tag:BiazhHGuF35gNCGRmIijdw==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:4n/Nu9P+tfG2Xgl9jWNHoeHJvg4SdLNuFu60bsna6FpbDI3uQfysBEea00QQSnI/eM9D+cON0B1Zkc0YLaqWoqf64hgahzw1hlJtB/ueO7sxcop+cw==,iv:8JU/QDL36HnYga9sT4gZnHMxH7l+MpwhntTjOf0fZqs=,tag:MLbb33rUdp+LNAbq5vqFaw==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:/UWXOszYKFzcPIKLxxZV6hck3jv3tXEnXPLHuNq/C5iyDiQc9JCewYflAivgV82fKmfJAgKfIyDyWN8tYzqqYg==,iv:ySBfYiUCVkoGcIJItN9CtFPbRDVGXTZQQi5V0MMFfP8=,tag:AZK61AFc1DhSQ5aD5lyzVQ==,type:str]
    RESEND_API_KEY: ENC[AES256_GCM,data:XCSTHMrcoOyd,iv:lBJq8AW9KSZAYWdRBStTwdchWZbb8FVfNcREoTnHwlM=,tag:GpD72q6GTQqnP0Or++ln0w==,type:str]
    RESEND_FROM: ENC[AES256_GCM,data:guCr3e6UAi+l9B6BwuoPXmHa90Y=,iv:DLhSNsDUgJp2C+cD+EMibOHJ81OotcC0ZURTa3BDVqc=,tag:DeIu+25yaoRfNSVeeyYVIg==,type:str]
sops:
    age:
        - recipient: age1rt320uvjzf8jrx7xwy97gqh69jykx6650my54m4uycfs7vx37arqkpgrfu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRODRoZnErOFQwS0lMbGhF
            Mlhuam42dVpjOVRmZ1kydHhFS3BsTWJwTzNjCkVoUlF5SEpKazVzOHFDMGJLQkhL
            R3k2aHh6Qk44UzloZWxETUZIa3FaeGsKLS0tIEtFUXV1a093N0ZHRW1GeVpVcHNM
            NWNkT0lOTDROeEtxaGpOTCtQb2hmQTAKqg8MR3VyufGBaxf16uzvXZFGFmaF6XJ1
            imWr+r2/nO6YIlyoeNBbpbo5EEF3etqyQClVhLM4eOMqbQyLZPJIGQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-01T17:52:19Z"
    mac: ENC[AES256_GCM,data:VD4rMP4o1uoL4mCf4aDmKLZCqVa7lJ1jftNk8bl9c0AfHRzClkmSVptsA1cGupqzhGXI9UJsLhSlj1cw6lTG10ai8r/Y+EhOvM6Cn+iX8z1GZXLunKh879nVmLS/Rwuu96ix8KpP0nXsrpT0DDbtPcj8yw44k4cAbrbllA66fio=,iv:HU1tbHU1/5JdF0j9jPLmtml6J+lCSqSoQDhUmjDWoBo=,tag:qCXKpdMyxOEz3NnAoHB2Qg==,type:str]
    encrypted_regex: ^stringData$
    version: 3.12.1
