apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:Ig9yYlY=,iv:Fo/H4EDfjRwkXl5tZwUpeVFgpW8REE5DLoSV/WJk2aE=,tag:ZZkLAo4DjWZQofi0X3Eb1A==,type:str]
    admin-password: ENC[AES256_GCM,data:EhK0oev6w2+vKFWaWLgrnN49Tjj+frD7,iv:GGkzwjObtgQQ4YsHaCGoXtD/5aTdCzjmyxZXDJ15U9I=,tag:D2USFMgB77KrlABrG9sy6g==,type:str]
sops:
    age:
        - recipient: age1rt320uvjzf8jrx7xwy97gqh69jykx6650my54m4uycfs7vx37arqkpgrfu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmQjZINW1nSTJ0aWxWMm15
            UGNId3FieGdrOTVjalNtM2NvNmpSRVloaGljCnZPSWZyN2xtTkdLbURFemZvZDVk
            dGFHMEtEemdlU1JaOWUwYWFWNHhqVmcKLS0tIGRVVkpPRFV6VEozY1l6RTZIaCtK
            WE9oQnJ1L1hHV3ZoazlTdUUwVDZRODQKG4qomPCxCzlTYjaqXljE/uLLuF5PbUJZ
            e1znjSl9WRC4qBw+IqOgMC0/Kk6aYPG7tFLmC1aWXY8laLf3OSgp0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-01T17:52:22Z"
    mac: ENC[AES256_GCM,data:iMmIvT9qTIISvHudwFeCAqTWXhKC6yn6yzQFq4Wz48vB6gQHyxb+DsXcRl2LSLsK730Hb6TqNh0NOA8soyCIOvaptMM0CvgfRCjZZ5TYR17BK1uBboubNmz7S0Zm2mGw1kTc7Gh8IOM4QIfZqcVqeC+WhmtOZQ5mNJuG7NFHQbs=,iv:t7ShmUQr2uW1UBiwrlIuJLjOBpvranK4R1mvWk1jj4Y=,tag:EQXQaabskESqcR0gfJ8L7w==,type:str]
    encrypted_regex: ^stringData$
    version: 3.12.1
